module.exports = {
  "connections": [
    {
      "connection": {
        "id": "web_rvV1gJEUE82b",
        "team_id": "tm_uQ4WvhVHCEHA",
        "updated_at": "2024-04-08T18:37:27.092Z",
        "created_at": "2024-04-08T18:37:27.321Z",
        "paused_at": null,
        "name": null,
        "rules": [],
        "description": "Autogenerated from Vercel integration",
        "destination": {
          "id": "des_XgUbbyuUVq26",
          "team_id": "tm_uQ4WvhVHCEHA",
          "url": "https://nextjs-boilerplate-eta-five-30.vercel.app/webhook-handler",
          "updated_at": "2024-04-08T18:37:27.092Z",
          "created_at": "2024-04-08T18:37:27.098Z",
          "rate_limit": null,
          "rate_limit_period": "second",
          "cli_path": null,
          "path_forwarding_disabled": false,
          "name": "dst-omvik27p6o22crte",
          "http_method": null,
          "auth_method": {
            "type": "HOOKDECK_SIGNATURE",
            "config": {}
          },
          "description": "Autogenerated from Vercel integration",
          "disabled_at": null
        },
        "source": {
          "id": "src_3m26ikjxmyjkdi",
          "team_id": "tm_uQ4WvhVHCEHA",
          "updated_at": "2024-04-08T18:37:27.115Z",
          "created_at": "2024-04-08T14:43:26.584Z",
          "name": "from-vercel-v035",
          "allowed_http_methods": [
            "POST",
            "PUT",
            "PATCH",
            "DELETE"
          ],
          "custom_response": null,
          "description": "Autogenerated from Vercel integration",
          "url": "https://hkdk.events/3m26ikjxmyjkdi",
          "disabled_at": null,
          "verification": null
        },
        "disabled_at": null,
        "full_name": "from-vercel-v035 -> dst-omvik27p6o22crte"
      },
      "config": {
        "match": "/webhook-handler",
        "url": "https://nextjs-boilerplate-eta-five-30.vercel.app/webhook-handler",
        "api_key": "4rzpinn4gjfj1hxhlpc63ufhbeenrhq2z6y2bkwxqycnrhjvd5",
        "source_name": "from-vercel-v035",
        "path_forwarding_disabled": true
      },
      "source_name": "from-vercel-v035",
      "id": "web_rvV1gJEUE82b"
    }
  ]
};